export const dummyuser = [
	{
		id: 1,
		first_name: 'Oberon',
		last_name: 'Crofthwaite',
		email: 'ocrofthwaite0@japanpost.jp',
		gender: 'Male',
		role: ['admin'],
		password: 'high',
	},
	{
		id: 2,
		first_name: 'Paulie',
		last_name: 'Pena',
		email: 'ppena1@blogspot.com',
		gender: 'Female',
		role: ['farmer'],
		password: 'high',
	},
	{
		id: 3,
		first_name: 'Carlye',
		last_name: 'Slott',
		email: 'cslott2@bandcamp.com',
		gender: 'Female',
		role: ['customer'],
		password: 'high',
	},
	{
		id: 4,
		first_name: 'Bianka',
		last_name: 'Osmint',
		email: 'bosmint3@cloudflare.com',
		gender: 'Female',
		role: ['courier'],
		password: 'high',
	},
	{
		id: 5,
		first_name: 'Letisha',
		last_name: 'Zimmermanns',
		email: 'lzimmermanns4@wikipedia.org',
		gender: 'Female',
		role: ['admin'],
		password: 'high',
	},
	{
		id: 6,
		first_name: 'Tanney',
		last_name: 'Nutley',
		email: 'tnutley5@4shared.com',
		gender: 'Male',
		role: ['customer'],
		password: 'high',
	},
	{
		id: 7,
		first_name: 'Archie',
		last_name: 'Kassidy',
		email: 'akassidy6@fema.gov',
		gender: 'Male',
		role: ['farmer'],
		password: 'high',
	},
	{
		id: 8,
		first_name: 'Nichols',
		last_name: 'Godlip',
		email: 'ngodlip7@fastcompany.com',
		gender: 'Male',
		role: ['courier'],
		password: 'high',
	},
	{
		id: 9,
		first_name: 'Alric',
		last_name: 'Mancer',
		email: 'amancer8@sakura.ne.jp',
		gender: 'Male',
		role: ['admin'],
		password: 'high',
	},
	{
		id: 10,
		first_name: 'Ofilia',
		last_name: 'Booth',
		email: 'obooth9@wikipedia.org',
		gender: 'Female',
		role: ['customer'],
		password: 'high',
	},
];
